repos:
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-black
      - id: nbqa-pyupgrade
        args: ["--py310-plus"]
      - id: nbqa-isort
      - id: nbqa-flake8
        args: ["--extend-ignore=E402,E501,F821"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        description: Strip output from jupyter notebooks
        args: [--drop-empty-cells]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-builtin-literals
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
